apiVersion: batch/v1
kind: CronJob
metadata:
  name: todoapp-healthcheck
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl-health
            image: radial/busyboxplus:curl
            command:
            - /bin/sh
            - -c
            - "curl http://todoapp-service.todoapp.svc.cluster.local/api/health"
            resources:
              requests:
                cpu: "100m"
                memory: "64Mi"
              limits:
                cpu: "200m"
                memory: "128Mi"
          restartPolicy: OnFailure
