apiVersion: batch/v1
kind: CronJob
metadata:
  name: todoapp-health-cronjob
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl-container
            image: ikulyk404/busyboxplus:curl
            resources:
              requests:
                cpu: "100m"
                memory: "64Mi"
              limits:
                cpu: "200m"
                memory: "128Mi"
            command: ["curl"]
            args: ["http://todoapp-service.todoapp.svc.cluster.local/api/health"]
          restartPolicy: OnFailure
