apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: todoapp-pinger
  namespace: mateapp
spec:
  selector:
    matchLabels:
      app: todoapp-pinger
  template:
    metadata:
      labels:
        app: todoapp-pinger
    spec:
      containers:
      - name: pinger
        image: radial/busyboxplus:curl
        command:
        - /bin/sh
        - -c
        - |
          while true; do
            curl http://todoapp-service.todoapp.svc.cluster.local;
            sleep 5;
          done
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
